// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// TestRunListerExpansion allows custom methods to be added to
// TestRunLister.
type TestRunListerExpansion interface{}

// TestRunNamespaceListerExpansion allows custom methods to be added to
// TestRunNamespaceLister.
type TestRunNamespaceListerExpansion interface{}
