// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	jxtestv1alpha1 "github.com/jenkins-x/jx-test/pkg/apis/jxtest/v1alpha1"
	versioned "github.com/jenkins-x/jx-test/pkg/client/clientset/versioned"
	internalinterfaces "github.com/jenkins-x/jx-test/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/jenkins-x/jx-test/pkg/client/listers/jxtest/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// TestRunInformer provides access to a shared informer and lister for
// TestRuns.
type TestRunInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.TestRunLister
}

type testRunInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewTestRunInformer constructs a new informer for TestRun type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTestRunInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredTestRunInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredTestRunInformer constructs a new informer for TestRun type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredTestRunInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.JxtestV1alpha1().TestRuns(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.JxtestV1alpha1().TestRuns(namespace).Watch(options)
			},
		},
		&jxtestv1alpha1.TestRun{},
		resyncPeriod,
		indexers,
	)
}

func (f *testRunInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredTestRunInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *testRunInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&jxtestv1alpha1.TestRun{}, f.defaultInformer)
}

func (f *testRunInformer) Lister() v1alpha1.TestRunLister {
	return v1alpha1.NewTestRunLister(f.Informer().GetIndexer())
}
