// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/jenkins-x/jx-test/pkg/client/clientset/versioned/typed/jxtest/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeJxtestV1alpha1 struct {
	*testing.Fake
}

func (c *FakeJxtestV1alpha1) TestRuns(namespace string) v1alpha1.TestRunInterface {
	return &FakeTestRuns{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeJxtestV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
