// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/jenkins-x/jx-test/pkg/apis/jxtest/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTestRuns implements TestRunInterface
type FakeTestRuns struct {
	Fake *FakeJxtestV1alpha1
	ns   string
}

var testrunsResource = schema.GroupVersionResource{Group: "jxtest.jenkins.io", Version: "v1alpha1", Resource: "testruns"}

var testrunsKind = schema.GroupVersionKind{Group: "jxtest.jenkins.io", Version: "v1alpha1", Kind: "TestRun"}

// Get takes name of the testRun, and returns the corresponding testRun object, and an error if there is any.
func (c *FakeTestRuns) Get(name string, options v1.GetOptions) (result *v1alpha1.TestRun, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(testrunsResource, c.ns, name), &v1alpha1.TestRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TestRun), err
}

// List takes label and field selectors, and returns the list of TestRuns that match those selectors.
func (c *FakeTestRuns) List(opts v1.ListOptions) (result *v1alpha1.TestRunList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(testrunsResource, testrunsKind, c.ns, opts), &v1alpha1.TestRunList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TestRunList{ListMeta: obj.(*v1alpha1.TestRunList).ListMeta}
	for _, item := range obj.(*v1alpha1.TestRunList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested testRuns.
func (c *FakeTestRuns) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(testrunsResource, c.ns, opts))

}

// Create takes the representation of a testRun and creates it.  Returns the server's representation of the testRun, and an error, if there is any.
func (c *FakeTestRuns) Create(testRun *v1alpha1.TestRun) (result *v1alpha1.TestRun, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(testrunsResource, c.ns, testRun), &v1alpha1.TestRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TestRun), err
}

// Update takes the representation of a testRun and updates it. Returns the server's representation of the testRun, and an error, if there is any.
func (c *FakeTestRuns) Update(testRun *v1alpha1.TestRun) (result *v1alpha1.TestRun, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(testrunsResource, c.ns, testRun), &v1alpha1.TestRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TestRun), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTestRuns) UpdateStatus(testRun *v1alpha1.TestRun) (*v1alpha1.TestRun, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(testrunsResource, "status", c.ns, testRun), &v1alpha1.TestRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TestRun), err
}

// Delete takes name of the testRun and deletes it. Returns an error if one occurs.
func (c *FakeTestRuns) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(testrunsResource, c.ns, name), &v1alpha1.TestRun{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTestRuns) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(testrunsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.TestRunList{})
	return err
}

// Patch applies the patch and returns the patched testRun.
func (c *FakeTestRuns) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.TestRun, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(testrunsResource, c.ns, name, pt, data, subresources...), &v1alpha1.TestRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TestRun), err
}
